# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-19 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arch_reqs',
            fields=[
                ('id_arcreq', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Architecture',
            fields=[
                ('arch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, verbose_name='Описание особенностей архитектуры')),
            ],
        ),
        migrations.CreateModel(
            name='Def_cost',
            fields=[
                ('cost_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Def_price',
            fields=[
                ('price_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Def_type',
            fields=[
                ('type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(default=False, max_length=50, verbose_name='Описание типа затрат')),
            ],
        ),
        migrations.CreateModel(
            name='Defence',
            fields=[
                ('def_id', models.IntegerField(primary_key=True, serialize=False)),
                ('def_name', models.CharField(max_length=100, verbose_name='Название СрЗИ')),
                ('def_dev', models.CharField(max_length=40, verbose_name='Разработчик СрЗИ')),
                ('def_cert', models.DateField(verbose_name='Дата истечения сертификата ФСТЭК')),
                ('def_desc', models.CharField(max_length=500, verbose_name='Описание СрЗИ')),
                ('def_os', models.CharField(max_length=1, verbose_name='Флаг типа ОС')),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_id', models.CharField(max_length=5)),
                ('require', models.CharField(max_length=5, verbose_name='Название требования с СрЗИ из приказа ФСТЭК 21')),
                ('description', models.CharField(max_length=500, verbose_name='Описание требования к СрЗИ')),
                ('defensible', models.BooleanField(default=True, verbose_name='Закрывается ли программными методами')),
                ('pdn_lvl', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('cost_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Def_cost')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Электронная почта')),
                ('firstname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Фамилия')),
                ('lastname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя')),
                ('middlename', models.CharField(blank=True, max_length=40, null=True, verbose_name='Отчество')),
                ('birthDate', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('password', models.CharField(max_length=500, verbose_name='Пароль')),
                ('regDate', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Суперпользователь')),
            ],
        ),
        migrations.AddField(
            model_name='user_price',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Users'),
        ),
        migrations.AddField(
            model_name='defence',
            name='requirements',
            field=models.ManyToManyField(to='landing.Requirements'),
        ),
        migrations.AddField(
            model_name='def_price',
            name='def_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Defence'),
        ),
        migrations.AddField(
            model_name='def_price',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Def_type'),
        ),
        migrations.AddField(
            model_name='def_cost',
            name='price_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Def_price'),
        ),
        migrations.AddField(
            model_name='arch_reqs',
            name='arch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Architecture'),
        ),
        migrations.AddField(
            model_name='arch_reqs',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Requirements'),
        ),
    ]
