# Generated by Django 2.0.5 on 2018-05-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Электронная почта')),
                ('firstname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Фамилия')),
                ('lastname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя')),
                ('middlename', models.CharField(blank=True, max_length=40, null=True, verbose_name='Отчество')),
                ('birdDate', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('password', models.CharField(max_length=30, verbose_name='Пароль')),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Суперпользователь')),
            ],
        ),
    ]
